### ISSUE TITLE
License file expired?

### ISSUE THREAD

**Issue by nf9** [Lichee-Pi/Tang_FPGA_Examples#9]
Hello. I got an error.
Here is the console output:
CMD-004 : start command "optimize_rtl"
RUN-001 : Open license file D:/Anlogic/TD4.2.511/license/Anlogic.lic
RUN-003 ERROR: License expired!

Where could I get the license file? Reinstalling did not help.

**Comment by nf9** [comment]
changing the date on your computer works. but this is just a workaround. Where can I download the updated TD?

**Comment by xelll** [comment]
you should update Td, you can download by 
Lichee Tang:
url ：https://pan.baidu.com/s/1uOSH2XeLjPxiHLHaxN3_ig 
code ：q0lv

**Comment by nf9** [comment]
perfect. now I have the latest TD. thank you!

**Comment by aquaratixc** [comment]
Link for updated TD doesn't work

**Comment by xelll** [comment]
> Link for updated TD doesn't work

http://dl.sipeed.com/TANG/Primer/IDE/
you can download lastest at here

**Comment by nf9** [comment]
thank you!

**Comment by Renha** [comment]
I could not, 404 error

**Comment by xelll** [comment]
> I could not, 404 error

http://dl.sipeed.com/TANG

then, found Premier and IDE

**Comment by maludwig** [comment]
I solved this on Windows by going here:

https://dl.sipeed.com/TANG/Primer/IDE

Downloading the new license file "Anlogic_202003.lic", and putting it into the "C:\Anlogic\TD4.4.433\license\" directory, and then renaming it to be just "Anlogic.lic", to replace the old license.

**Comment by nuee-ardente** [comment]
Hi, 
In 2021 the Anlogic_202003.lic is not working.
Is it necessary to get it from the following link?
http://www.anlogic.com/down_view.aspx?TypeId=22&Id=459&Fid=t14:22:14
